@APBD_TEST_2_C_HostAddress = http://localhost:5220

### GET valid racer participations - ok
GET http://localhost:5220/api/racers/1/participations
Accept: application/json


### POST valid participation - ok
POST http://localhost:5220/api/track-races/participants
Content-Type: application/json

{
  "raceName": "Monaco Grand Prix",
  "trackName": "Monaco Circuit",
  "laps": 78,
  "participations": [
    {
      "racerId": 1,
      "position": 1,
      "finishTimeInSeconds": 5400
    },
    {
      "racerId": 2,
      "position": 2,
      "finishTimeInSeconds": 5500
    }
  ]
}


### POST with non-existent racer - false
POST http://localhost:5220/api/track-races/participants
Content-Type: application/json

{
  "raceName": "Monaco Grand Prix",
  "trackName": "Monaco Circuit",
  "laps": 78,
  "participations": [
    {
      "racerId": 999,
      "position": 1,
      "finishTimeInSeconds": 5200
    }
  ]
}


### POST with missing fields (invalid model) - false
POST http://localhost:5220/api/track-races/participants
Content-Type: application/json

{
  "trackName": "Monaco Circuit",
  "participations": [
    {
      "position": 1,
      "finishTimeInSeconds": 5200
    }
  ]
}


### POST with negative laps - false
POST http://localhost:5220/api/track-races/participants
Content-Type: application/json

{
  "raceName": "British Grand Prix",
  "trackName": "Silverstone Circuit",
  "laps": -10,
  "participations": [
    {
      "racerId": 1,
      "position": 3,
      "finishTimeInSeconds": 6000
    }
  ]
}


